### ISSUE TITLE
access-control-allow-origin: * not set on /jokes/search endpoint

### ISSUE THREAD

**Issue by NotMyself** [chucknorris-io/chuck-api#12]
I was working on a sample application using your awesome API and discovered that the search endpoint does not properly have the `access-control-allow-origin: *` header set.

Here is the curl output.

![screen shot 2018-02-07 at 9 12 23 am](https://user-images.githubusercontent.com/73120/35930638-51c42aec-0be7-11e8-9d56-80b906e425c0.png)

**Comment by NotMyself** [comment]
After playing around with this for a while, I figured out I was sending the request incorrectly. I was not properly adding the query string value. if you hit `/jokes/search` you get the CORS error. if you hit `/jokes/search?query=poop` you do not.

**Comment by matchilling** [comment]
Hi @NotMyself, thanks for submitting your observations. I'll change the status code and return a `422` if the `query` parameter is missing and add also the CORS header to the response.

**Comment by NotMyself** [comment]
FYI, here is what I was working on.

https://www.youtube.com/watch?v=Tm0Cg5u1Zjo
