### ISSUE TITLE
Support free text search and random joke by category on '/random' endpoint

### ISSUE THREAD

**Issue by matchilling** [chucknorris-io/chuck-api#2]
As an api consumer of the '/random' endpoint I want to be able to search random jokes by a given category and free text search (c.f. slack endpoint).

Request from [@marceloverdijk](https://twitter.com/marceloverdijk/status/782129803675758592)

**Comment by marceloverdijk** [comment]
Also api endpoint for retrieving categories would be nice.

**Comment by matchilling** [comment]
Resolved in [2381d0a5bb4671fe641d9ca82d60b61f8a12ee82](https://github.com/chucknorris-io/chuck-api/commit/2381d0a5bb4671fe641d9ca82d60b61f8a12ee82) & [2a54e5c3a37bb1a5238b2363a076da44010b21c0](https://github.com/chucknorris-io/chuck-api/commit/2a54e5c3a37bb1a5238b2363a076da44010b21c0)

**Comment by marceloverdijk** [comment]
Thx!

**Comment by matchilling** [comment]
@marceloverdijk, you're welcome

```sh
// Add an optional `category` parameter to get a random joke from the given category
$ curl --request GET \
       --url 'https://api.chucknorris.io/jokes/random?category=dev' \
       --header 'content-type: application/json'

// Retrieve a list of available categories
$ curl --request GET \
       --url 'https://api.chucknorris.io/jokes/categories' \
       --header 'content-type: application/json'

// Free text search
$ curl --request GET \
       --url 'https://api.chucknorris.io/jokes/search?query={query}' \
       --header 'content-type: application/json'
```
