### ISSUE TITLE
spelling in some responses

### ISSUE THREAD

**Issue by chuckreynolds** [chucknorris-io/chuck-api#20]
ID: `vxmg5zgusq6ra35ns4e5sw`

change `unscrathed` => `unscathed`

**Comment by chuckreynolds** [comment]
that said... any way to check/correct spelling on all?

**Comment by chuckreynolds** [comment]
ID: `zk14uc6xr82d7ig9qhaymg`

change `let\'s` => `lets`

**Comment by matchilling** [comment]
@chuckreynolds thanks for reporting the spellings. Very much appreciated! They’re both fixed and I'm thinking about a mechanism to make the "edit" functionality publicly available.
