### ISSUE TITLE
thoughts? normalize occurrences of "Chuck Norris" instead of "Chuck" or..

### ISSUE THREAD

**Issue by chuckreynolds** [chucknorris-io/chuck-api#22]
**Primary Example:**  id: `wwejtx8ascmzfkc6gjqmqa` == 
```
...know that Chuck doesn\'t want fries with...
```

Some scripts are replacing "Chuck Norris" with a custom name... let's just say Jimbo for example.  When things like just "Chuck" (-Norris) show up in response.value it'd make it easier if all occurrences were the full name.  Thoughts on that? 

**Secondary Example**
Possibly another issue but it's hard to change results with things like "chucktanium" `https://api.chucknorris.io/jokes/search?query=chucktanium` OR "Norriscope" etc... This one is more for the "thought" to see if just ignore them and deal with it or thoughts on str.replace for those?

**Comment by chuckreynolds** [comment]
right now I just have this working - idk if it's the best option but... 

```js
let fact = response.data.value
fact = fact.replace(new RegExp('Chuck Norris', 'gi'), 'Jimbo') // replace all matches w/case-insensitive flag
fact = fact.replace(new RegExp('Chuck', 'gi'), 'Jimbo') // replace single "chuck" instances
```

**Comment by matchilling** [comment]
HI @chuckreynolds, the official Chuck Norris Slack app has this capability already (see https://slack.com/apps/A0S3YNZ2S-chuck-norris `Type /chuck @{user_name} to get a random personalised joke.`).

I'll add the functionality to the public api so that you'll be able to call the endpoint like this:
```shell
curl -X GET \
  'http://localhost:8080/jokes/random?name=Bob' \
  -H 'Accept: application/json'
```

```json
{
    "categories": [
        "dev"
    ],
    "created_at": "2016-05-01 10:51:41.584544",
    "icon_url": "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
    "id": "og4cu6e3teuwvlhnezj37w",
    "updated_at": "2016-05-01 10:51:41.584544",
    "url": "https://api.chucknorris.io/jokes/og4cu6e3teuwvlhnezj37w",
    "value": "Bob doesn't use web standards as the web will conform to him."
}
```

**Comment by chuckreynolds** [comment]
Cool! that'd be helpful. :)

**Comment by matchilling** [comment]
@chuckreynolds,  with the [latest version](https://github.com/chucknorris-io/chuck-api/pull/23) you're now be able to retrieve a random personalised joke as described above.

✌️

**Comment by chuckreynolds** [comment]
example of issue using this; id:`ZHlFVdh5Rrutc3GXNvzjsQ` still says chuck norris (also a misspelling of *first)

```
the firt rule of Bob clearly states...  NOT TO TALK ABOUT CHUCK NORRIS!!!
```

**Comment by matchilling** [comment]
Hi 👋, thanks for the prompt feedback! I've optimised the SQL query with the latest [release which](https://github.com/chucknorris-io/chuck-api/commit/e41d2410738aec3fd00e99979a501fb4181ccf11) is now live.

**Comment by matchilling** [comment]
@chuckreynolds with the latest release (429cf619e53355c0e7b3e7a262a8b6faf2be1f41) you can additionally retrieve a random personalised fact by one or more categories. For example:

```shell
$ curl --request GET \
       --url 'https://api.chucknorris.io/jokes/random?name=Bob&category=dev,explicit' \
       --header 'accept: application/json'
```

```json
{
    "categories": [
        "dev"
    ],
    "created_at": "2016-05-01 10:51:41.584544",
    "icon_url": "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
    "id": "wwnk3xvkriigmvndrzv-ew",
    "updated_at": "2016-05-01 10:51:41.584544",
    "url": "https://api.chucknorris.io/jokes/wwnk3xvkriigmvndrzv-ew",
    "value": "Bob can spawn threads that complete before they are started."
}
```
```json
{
    "categories": [
        "explicit"
    ],
    "created_at": "2016-05-01 10:51:41.584544",
    "icon_url": "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
    "id": "VEDOQuIsSI-2CAgq3-2DaQ",
    "updated_at": "2019-06-09 00:45:41.225627",
    "url": "https://api.chucknorris.io/jokes/VEDOQuIsSI-2CAgq3-2DaQ",
    "value": "Bob is all for same-sex marriage, as long as both chicks are hot."
}
```

Happy coding ✌️

**Comment by chuckreynolds** [comment]
updated bot code. TY!
