### ISSUE TITLE
more that should have explicit cat 

### ISSUE THREAD

**Issue by chuckreynolds** [chucknorris-io/chuck-api#29]
had one of these turn up in chat... eeeeks...  Should make sure all with "raped" have explicit category please so we can not have those. 

https://api.chucknorris.io/jokes/search?query=raped

**Comment by matchilling** [comment]
Hej hej @chuckreynolds 👋 ,

Sorry for the delayed reply ~ I've updated the jokes in question accordingly with the "explicit" category.

Bests,
Mathias
