### ISSUE TITLE
Web-view, missing trailing comma in JSON response example

### ISSUE THREAD

**Issue by stunney** [chucknorris-io/chuck-api#32]
Website shows the following "Example response:" for a simple HTTP GET
```
{
"icon_url" : "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
"id" : "Wr8L3n8jTYqxAzN17tfFew",
"url" : ""
"value" : "Chuck Norris can slice meat so thin it only has one side."
}
```

This is invalid JSON.  The contents are missing a comma (,) at the end of the url line.

**Comment by matchilling** [comment]
Hey @stunney 👋, Thanks for opening this issue - the JSON example has been fixed [here](https://github.com/chucknorris-io/chuck-api/commit/38bf2da518a3f9dfb1f96f9a91f764f7caf67adb).

**Comment by stunney** [comment]
Excellent!
