### ISSUE TITLE
Money category doesn't allow names to be swapped out - Bad HTTP response code

### ISSUE THREAD

**Issue by stunney** [chucknorris-io/chuck-api#33]
https://api.chucknorris.io/jokes/categories returns "money" as a valid category

if I were to

`curl --request GET --url 'https://api.chucknorris.io/jokes/random?category=money' --header 'accept: application/json'`
I would get a 200 and a joke.  Yay.

if I were to
`curl --request GET --url 'https://api.chucknorris.io/jokes/random?category=money&name=Bob' --header 'accept: application/json'`
I would receive a very cryptic and incorrect 404

Even on your website I get a 404

> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Thu May 21 22:32:00 UTC 2020
> There was an unexpected error (type=Not Found, status=404).
> No personalized jokes for name "Bob" and category "money" found.

If I switch the category only to "history" I get a valid joke response.

**Comment by matchilling** [comment]
Hey @stunney  👋, Thanks for opening this issue.

The reason why you weren't receiving personalised jokes for the money category was that there were just no qualifying jokes to satisfy the query, hence the 404.

However, I've categorised some jokes accordingly, and you should now get them with the query which you've mentioned above.

Cheers,
M
