### ISSUE TITLE
Strings are not escaped

### ISSUE THREAD

**Issue by Ahmadre** [chucknorris-io/chuck-api#36]
I use this api in our CI/CD Pipeline and we got JSON errors that it's invalid, because of some jokes where strings are not escaped.

Example:

```
Chuck Norris was asked if he would date Rosie O'\''Donnell? Chuck said "I'\''d rather shove a lit match up my pee-hole"
```

The error lies here: `'\''Donnell? Chuck said "I'\''d`

**Comment by Ahmadre** [comment]
solved it with `jq '.value | tostring'`

**Comment by matchilling** [comment]
Hey @Ahmadre, thanks for using the Chuck Norris api and for reporting this issue. Please note that all api endpoints can return plain text as well, just add `accept: text/plain` to your request and you'll get a plain text representation for the given resource. E.g.

```shell
curl --request GET \
       --url 'https://api.chucknorris.io/jokes/random' \
       --header 'accept: text/plain'
```

Hope this helps 🙏 

Bests,
Matías

**Comment by Ahmadre** [comment]
Thanks for your reply it worked after I found that :)

**Comment by Ahmadre** [comment]
Our Team and Devs loves this in our CI-Reports!

You guys rock!
