### ISSUE TITLE
How to report a Chuck Norris joke that has improper english?

### ISSUE THREAD

**Issue by shadoath** [chucknorris-io/chuck-api#40]
First of all, thank you. I enjoy these showing up at my work. One of the best easter eggs I have put into production code.

Now to the question. I don't see a way to correct an issue with a specific Chuck Norris joke:

>Chuck Norris does not need to type-cast. The Chuck-Norris Compiler (CNC) sees through things. All way down. Always.

I think this should be:

>Chuck Norris does not need to type-cast. The Chuck-Norris Compiler (CNC) sees through things. All the way down. Always.

**Comment by matchilling** [comment]
Hey @shadoath, glad you're enjoying the daily doses of Chuck Norris jokes, and I apologise for not getting back to you earlier. Also, thanks for your contribution; I've updated the [source accordingly](https://api.chucknorris.io/jokes/wft-ksbrqncyrcg0k8cpzw).

**Comment by shadoath** [comment]
Thank you!
