### ISSUE TITLE
How to retrieve a specific joke?

### ISSUE THREAD

**Issue by dnaeon** [chucknorris-io/chuck-api#8]
I'd like to be able to retrieve a joke with specific id, is that possible?

The main reason for this is to include this as part of the tests in my tool, so if I'm able to retrieve a specific joke then I can compare the results in my tests.

For example what would be the API endpoint for this joke with id `bdo-g3sjtowgdeneipfgrg`?

* https://api.chucknorris.io/jokes/bdo-g3sjtowgdeneipfgrg

**Comment by manicmaniac** [comment]
@dnaeon It can be achieved by using the endpoint you referred, if you explicitly request JSON as response.

Try `curl --header 'Accept: application/json' https://api.chucknorris.io/jokes/bdo-g3sjtowgdeneipfgrg`.

**Comment by dnaeon** [comment]
Thanks!
